### ISSUE TITLE
Needs upgrade to Smolder v10.1

### ISSUE THREAD

**Issue by justinwoo** [sharkdp/purescript-flarecheck#12]
I don't know how to do this without the monoid instance being there other than to write some boilerplate on cramming more things into MarkupM through liftF or whatnot though. Is there supposed to be an obvious way to do this?

**Comment by sharkdp** [comment]
Could you elaborate what you mean by "needs upgrade"? Is something broken, currently?

**Comment by justinwoo** [comment]
I need this package to be updated for inclusion in the new package set in https://github.com/purescript/package-sets/pull/111/files

**Comment by sharkdp** [comment]
I will probably not have time to work on this anytime soon. However, if you would like to contribute a PR, let me know if I can help.

**Comment by justinwoo** [comment]
I guess we fixed this a while ago.
